version: '3'
services:

  mariadb:
    networks:
    - inception
    build: requirements/mariadb
    env_file: .env
    ports:
    - "3306:3306"
    # volumes:
      # - /home/mthiesso/data/mariadb_volume:/var/lib/mysql
    restart:  unless-stopped

  nginx:
    container_name: nginx
    # volumes:
      # - /home/mthiesso/data/wp_volume:/var/www/html
    networks:
    - inception
    depends_on:
    - wordpress
    build:  requirements/nginx
    env_file: .env
    ports:
    - "443:443"
    restart:  on-failure
  
  wordpress:
    env_file: .env
    ports:
    - "9000:9000"
    # volumes:
      # - /home/mthiesso/data/wp_volume:/var/www/html
    networks:
    - inception
    build:  requirements/wordpress
    depends_on:
    - mariadb
    restart:  on-failure

networks:
  inception: