services:

  mariadb:
    networks:
    - inception
    build: requirements/mariadb
    env_file: .env
    ports:
    - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart:  unless-stopped

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
    - inception
    depends_on:
    - wordpress
    build:  requirements/nginx
    env_file: .env
    ports:
    - "443:443"
    restart:  on-failure
  
  wordpress:
    env_file: .env
    ports:
    - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
    - inception
    build:  requirements/wordpress
    depends_on:
    - mariadb
    restart:  on-failure

networks:
  inception:

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    name: mariadb
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'